# Navigation Bar Links
#   The weight parameter defines the order that the links will appear in.

[[main]]
    name = "Packages"
    url = "/packages/"
    weight = 1
[[main]]
    name = "tm blog"
    url = "/blog/"
    weight = 2
[[main]]
    name = "tv blog"
    url = "https://www.tidyverse.org/blog/"
    weight = 3
[[main]]
    name = "Learn"
    url = "https://www.tidyverse.org/learn/"
    weight = 4
[[main]]
    name = "Help"
    url = "https://www.tidyverse.org/help/"
    weight = 5
[[main]]
    name = "Contribute"
    url = "https://www.tidyverse.org/contribute/"
    weight = 6
