# Navigation Bar Links
#   The weight parameter defines the order that the links will appear in.

[[main]]
    name = "Packages"
    url = "/packages/"
    weight = 1
[[main]]
    name = "Get Started"
    url = "/examples/"
    weight = 2
[[main]]
    name = "Learn"
    url = "/learn/"
    weight = 7
[[main]]
    name = "Help"
    url = "/help/"
    weight = 8
[[main]]
    name = "Contribute"
    url = "/contribute/"
    weight = 9
[[main]]
    name = "GitHub"
    url = "https://github.com/tidymodels/"
    weight = 10
