# Navigation Bar Links
#   The weight parameter defines the order that the links will appear in.

[[main]]
    name = "Packages"
    url = "/packages/"
    weight = 1
[[main]]
    name = "Examples"
    url = "/examples/"
    weight = 2
[[main]]
    name = "Compendium"
    url = "/compendium/"
    weight = 3     
[[main]]
    name = "Books"
    url = "/books/"
    weight = 4          
[[main]]
    name = "Tidyverse blog"
    url = "https://www.tidyverse.org/blog/"
    weight = 5
[[main]]
    name = "Learn"
    url = "https://www.tidyverse.org/learn/"
    weight = 6
[[main]]
    name = "Help"
    url = "https://www.tidyverse.org/help/"
    weight = 7
[[main]]
    name = "Contribute"
    url = "https://www.tidyverse.org/contribute/"
    weight = 8
