# Description for social sharing and search engines.
description = "The tidymodels packages make the process of creating high-quality models easier."

# Default image for social sharing and search engines. Place image in `static/images/` folder and specify image name here.
sharing_image = "01.rstudio.flowers-sharing.jpg"
twitter_image = "01.rstudio.flowers-sharing.jpg"

# Link custom CSS and JS assets
#   (relative to /static/css and /static/js respectively)
custom_css = ["tm.css"]

# Define base hex url for index page (where the stickers link out to)
hex_base_url = "tidymodels.github.io/"
    
# Define "news" as both articles and events
mainSections = ["articles", "events"]

# options for highlight.js (version, additional languages, and theme)
highlightjsVersion = "9.11.0"
highlightjsCDN = "//cdn.bootcss.com"
highlightjsLang = ["r", "yaml"]
highlightjsTheme = "github"

MathJaxCDN = "//cdn.bootcss.com"
MathJaxVersion = "2.7.1"

[footer]
    github_url = "https://github.com/tidymodels"
    twitter_url = "https://twitter.com/hashtag/rstats"
    support = "Proudly supported by"

# leave blank in quotes for the default = true
# to turn off, set = false (no quotes)
[authors]
    show_list = "" # on list page, default is true
    show_single = "" # on single pages, default is true
    show_latest = "" # on bio, default is true
    label_latest = "" # on bio, default is "Latest"

# leave blank in quotes for the default = true
# to turn off, set = false (no quotes)
[events]
    link_archive = "" # default is true

# customize your site colors
# these colors get applied by layouts/partials/custom-site.css
# then, the layouts/partials/head_includes.html uses that partial
# the partial head_includes.html is called in the partial header.html everywhere!
[colors]
    text = "#1a1917" # black
    # Links
    link = "#ff414b" # red salmon
    link_hover = "#f97b82" #lighter
    # Footer
    footer_primary = "#00000026" # grayish variety of the accent
    footer_text = "#fcfcfc" 
    # Backgrounds
    background = "white" 
    home_section_odd = "#fcfcfc"
    home_section_even = "#ca225e" #recipe cupcake's pink
    # Menu
    menu_primary = "#fcfcfc" # modified to lighter navy
    menu_text = "black"
    menu_text_active = "#ff414b"
    menu_text_current = "#ff414b" # --does this show up?
    menu_decorate_current = "none"
    menu_title = "#141227" # Tidymodels navy/black
    menu_title_active = "#ff414b" # salmon
    menu_box_hover = "#fcfcfc" 
    menu_box_active = "#fcfcfc" 
    # Tables
    header_background = "#dfe3eb"
    table_row_even = "#f7faff"
    table_row_odd = "#fff"
